require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/answers", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Answer. As you add validations to Answer, be sure to
  # adjust the attributes here as well.
  let(:member) { Member.create(
    name: "MEmbro de Teste",
    registration: '11221442',
    username: "membro123",
    occupation: "Testador",
    degree: '-',
    course: '-',
    email: 'Testemebro@email.com'
  )}
  let(:cclass){ Cclass.create(
    code: "12334",
    semester:"2020/1",
    time:"2020",
    subject_id: subject.id
  )}
  let(:subject){ Subject.create(
    code: "332788913/2",
    name: "Matéria de Teste"
  )}
  let(:avaliation){ Avaliation.create(
    title: "Avaliação",
    cclass_id: cclass.id,
    )}
  let(:option) { Option.create(
    description: "Descrição para testar uma opção",
    avaliation_id: avaliation.id
  )}
  let(:valid_attributes) {
    {
      alternative_answer: 1,
      option_id: option.id,
      member_id: member.id
    }
  }

  let(:invalid_attributes) {
    {
      alternative_answer: 1,
      member_id: nil,
      option_id: nil,
    }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # AnswersController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Answer.create! valid_attributes
      get answers_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      answer = Answer.create! valid_attributes
      get answer_url(answer), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Answer" do
        expect {
          post answers_url,
               params: { answer: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Answer, :count).by(1)
      end

      it "renders a JSON response with the new answer" do
        post answers_url,
             params: { answer: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Answer" do
        expect {
          post answers_url,
               params: { answer: invalid_attributes }, as: :json
        }.to change(Answer, :count).by(0)
      end

      it "renders a JSON response with errors for the new answer" do
        post answers_url,
             params: { answer: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested answer" do
        answer = Answer.create! valid_attributes
        patch answer_url(answer),
              params: { answer: new_attributes }, headers: valid_headers, as: :json
        answer.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the answer" do
        answer = Answer.create! valid_attributes
        patch answer_url(answer),
              params: { answer: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the answer" do
        answer = Answer.create! valid_attributes
        patch answer_url(answer),
              params: { answer: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested answer" do
      answer = Answer.create! valid_attributes
      expect {
        delete answer_url(answer), headers: valid_headers, as: :json
      }.to change(Answer, :count).by(-1)
    end
  end
end
